FROM python:latest
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN install -d -m 0775 -o app_user -g app_user /static
RUN install -d -m 0775 -o app_user -g app_user /media
RUN install -d -m 0775 -o app_user -g app_user /app

COPY . /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir wheel && \
	pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir uvicorn[standard] && \
    pip install --no-cache-dir psycopg2-binary


# 运行多个 Python 脚本
CMD ["python", "test_send_to_kafka.py", "test_consume_from_kafka.py"]
