version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - TZ=Europe/Berlin
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_RETENTION_MS=50000
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=300000
      # - KAFKA_CFG_LOG_DIRS=/tmp
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
  postgres:
    image: 'postgres'
    restart: 'always'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=notsosecret
      - POSTGRES_USER=SmartWelding
      - POSTGRES_DB=SmartWelding
    ports:
      - "5432:5432"
