# Generated by Django 4.1 on 2024-02-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='machines/images', verbose_name='Image')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Topic')),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='machines/models', verbose_name='3D Model')),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('x_position', models.FloatField(default=0, help_text='x position of the machine in the parent coordinate system')),
                ('y_position', models.FloatField(default=0, help_text='x position of the machine in the parent coordinate system')),
                ('z_position', models.FloatField(default=0, help_text='x position of the machine in the parent coordinate system')),
                ('x_size', models.FloatField(default=0)),
                ('y_size', models.FloatField(default=0)),
                ('z_size', models.FloatField(default=0)),
                ('ex_base_vector', models.CharField(default='1 0 0', max_length=32)),
                ('ey_base_vector', models.CharField(default='0 1 0', max_length=32)),
                ('ez_base_vector', models.CharField(default='0 0 1', max_length=32)),
                ('role', models.CharField(blank=True, choices=[('ROBOT', 'robot'), ('TABLE', 'table'), ('WELDING', 'welding'), ('BOX', 'IIoT Box'), ('SWITCH', 'switch'), ('WAGO', 'wago'), ('ROOM', 'room'), ('WENGLOR', 'wenglor profile sensor')], max_length=32, null=True, verbose_name='role')),
                ('connected_robot', models.ForeignKey(blank=True, limit_choices_to={'role': 'ROBOT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectednode', to='postgreSQL.machine', verbose_name='connected robot')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postgreSQL.location', verbose_name='Location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='postgreSQL.machine', verbose_name='parent')),
            ],
        ),
        migrations.CreateModel(
            name='MachineParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='display name')),
                ('unit', models.CharField(blank=True, max_length=255, verbose_name='unit')),
                ('min_value', models.FloatField(blank=True, help_text='Minimal value for this Parameter. Required to calculate the relative value, If empty the relative value will be null', null=True, verbose_name='min value')),
                ('max_value', models.FloatField(blank=True, help_text='Maximal value for this Parameter. Required to calculate the relative value, If empty the relative value will be null', null=True, verbose_name='max value')),
                ('role', models.CharField(blank=True, choices=[('x_coordinate', 'x coordinate'), ('y_coordinate', 'y coordinate'), ('z_coordinate', 'z coordinate'), ('x_rotation', 'x rotation'), ('y_rotation', 'y rotation'), ('z_rotation', 'z rotation'), ('lan_port', 'lan port'), ('connection', 'connection')], max_length=32, null=True, verbose_name='role')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='postgreSQL.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinevalue', to='postgreSQL.machineparameter')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTextValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinetextvalue', to='postgreSQL.machineparameter')),
            ],
        ),
    ]
